import { db } from "./db.js";

const json=(v:unknown)=>JSON.stringify(v ?? {});
export async function getBusinessKnowledge(businessId:string){const [profile,compliance,experience,assets,documents,policy,business]=await Promise.all([db.query("SELECT * FROM business_profiles WHERE business_id=$1",[businessId]),db.query("SELECT * FROM business_compliance_records WHERE business_id=$1 ORDER BY expires_at NULLS LAST,name",[businessId]),db.query("SELECT * FROM business_experience_records WHERE business_id=$1 ORDER BY end_date DESC NULLS LAST,project_name",[businessId]),db.query("SELECT * FROM business_bid_assets WHERE business_id=$1 ORDER BY asset_type,name",[businessId]),db.query("SELECT * FROM business_knowledge_documents WHERE business_id=$1 ORDER BY updated_at DESC",[businessId]),db.query("SELECT * FROM business_operating_policies WHERE business_id=$1",[businessId]),db.query("SELECT id,slug,name,status,qualification_profile FROM businesses WHERE id=$1",[businessId])]);if(!business.rows[0])return null;return {business:business.rows[0],profile:profile.rows[0]??null,compliance:compliance.rows,experience:experience.rows,assets:assets.rows,documents:documents.rows,operatingPolicy:policy.rows[0]??null};}

export async function upsertBusinessProfile(id:string,input:Record<string,unknown>){const r=await db.query("INSERT INTO business_profiles (business_id,legal_name,trading_name,business_type,registration_number,tax_number,registration_jurisdiction,website,addresses,contact_details,authorized_representatives,services,industries,technical_capabilities,delivery_capabilities,geographic_coverage,staffing_capacity,equipment_resources,partners_subcontractors) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14::jsonb,$15::jsonb,$16::jsonb,$17::jsonb,$18::jsonb,$19::jsonb) ON CONFLICT (business_id) DO UPDATE SET legal_name=EXCLUDED.legal_name,trading_name=EXCLUDED.trading_name,business_type=EXCLUDED.business_type,registration_number=EXCLUDED.registration_number,tax_number=EXCLUDED.tax_number,registration_jurisdiction=EXCLUDED.registration_jurisdiction,website=EXCLUDED.website,addresses=EXCLUDED.addresses,contact_details=EXCLUDED.contact_details,authorized_representatives=EXCLUDED.authorized_representatives,services=EXCLUDED.services,industries=EXCLUDED.industries,technical_capabilities=EXCLUDED.technical_capabilities,delivery_capabilities=EXCLUDED.delivery_capabilities,geographic_coverage=EXCLUDED.geographic_coverage,staffing_capacity=EXCLUDED.staffing_capacity,equipment_resources=EXCLUDED.equipment_resources,partners_subcontractors=EXCLUDED.partners_subcontractors,updated_at=NOW() RETURNING *",[id,input.legalName??null,input.tradingName??null,input.businessType??null,input.registrationNumber??null,input.taxNumber??null,input.registrationJurisdiction??null,input.website??null,json(input.addresses??[]),json(input.contactDetails??{}),json(input.authorizedRepresentatives??[]),json(input.services??[]),json(input.industries??[]),json(input.technicalCapabilities??[]),json(input.deliveryCapabilities??[]),json(input.geographicCoverage??[]),json(input.staffingCapacity??{}),json(input.equipmentResources??[]),json(input.partnersSubcontractors??[])]);return r.rows[0];}

export async function upsertOperatingPolicy(id:string,input:Record<string,unknown>){const r=await db.query("INSERT INTO business_operating_policies (business_id,allowed_actions,prohibited_actions,commercial_limits,escalation_conditions,learning_boundaries,policy_restrictions) VALUES ($1,$2::jsonb,$3::jsonb,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb) ON CONFLICT (business_id) DO UPDATE SET allowed_actions=EXCLUDED.allowed_actions,prohibited_actions=EXCLUDED.prohibited_actions,commercial_limits=EXCLUDED.commercial_limits,escalation_conditions=EXCLUDED.escalation_conditions,learning_boundaries=EXCLUDED.learning_boundaries,policy_restrictions=EXCLUDED.policy_restrictions,updated_at=NOW() RETURNING *",[id,json(input.allowedActions??[]),json(input.prohibitedActions??[]),json(input.commercialLimits??{}),json(input.escalationConditions??[]),json(input.learningBoundaries??[]),json(input.policyRestrictions??[])]);return r.rows[0];}

const config={compliance:{table:"business_compliance_records",json:[]},experience:{table:"business_experience_records",json:["services","industries","reference_details"]},asset:{table:"business_bid_assets",json:[]},document:{table:"business_knowledge_documents",json:["metadata"]}} as const;
export async function insertRecord(kind:keyof typeof config,businessId:string,input:Record<string,unknown>){const c=config[kind];const columns=Object.keys(input).filter(k=>/^[a-z_]+$/.test(k));if(!columns.length)throw new Error("No record fields supplied");const values=columns.map(k=>c.json.includes(k as never)?json(input[k]):input[k]);const placeholders=columns.map((_,i)=>`$${i+2}${c.json.includes(columns[i] as never)?"::jsonb":""}`).join(",");const r=await db.query(`INSERT INTO ${c.table} (business_id,${columns.join(",")}) VALUES ($1,${placeholders}) RETURNING *`,[businessId,...values]);return r.rows[0];}
export async function deleteRecord(kind:keyof typeof config,id:string,businessId:string){await db.query(`DELETE FROM ${config[kind].table} WHERE id=$1 AND business_id=$2`,[id,businessId]);}